Remove cc_library deps from the exposed targets (#9)
Fixes this error for the 600.0.0 release:

```
ERROR: /private/var/tmp/_bazel_jszumski/ed7e7efa198ffcfaf8285220a74bc6f4/external/swift-syntax~/BUILD.bazel:247:13: in deps attribute of swift_import rule @@swift-syntax~//:SwiftSyntax_opt: rule '@@swift-syntax~//:_SwiftSyntaxCShims_opt' does not exist
```

The `cc_library` targets don't need to be exposed and they don't have an
automatic `_opt` version either.